### PR TITLE
Added gradle build files

### PR DESCRIPTION
**Pull request by jitpack**
To make it easier to build from command line and https://jitpack.io : )

### CODE REVIEW

**Comment by jitpack-io** [comment]
Updated PR

**Comment by jitpack-io** [comment]
Nice! It now builds just great on: https://jitpack.io/#baoyongzhang/SwipeMenuListView/42511d73fb
Would be even easier to use if there was a new GitHub release of SwipeMenuListView

**Comment by deM1d** [comment]
Does anybody test it? Try to add  this as dependency and it does not work. What I do wrong?
maven {
    url "https://jitpack.io"
}

compile 'com.github.baoyongzhang:SwipeMenuListView:v1.0.2'

**Comment by jitpack-io** [comment]
@deM1d Yes. But the 1.0.2 version does not include the buildfile of this PR yet. Hoping for 1.0.3

**Pull request merged**
